name: 'Upload S3'
description: 'Uploads package to S3'
inputs:
  bucket:
    required: true
  product:
    required: true
  branch:
    required: true
  build:
    required: true

runs:
  using: "composite"
  steps:
    - name: Create tarball
      run: tar -C ./release -czvf release.tar.gz .
    - name: Upload release
      run: aws s3api put-object --bucket ${{ inputs.bucket }} --key ${{ inputs.product }}/${{ inputs.branch }}/${{ inputs.build }}/release.tar.gz --body release.tar.gz
      shell: bash
    - name: Upload installer features
      run: aws s3api put-object --bucket ${{ inputs.bucket }} --key ${{ inputs.product }}/${{ inputs.branch }}/${{ inputs.build }}/install/installer-features.txt --body installer-features.txt
      shell: bash
    - name: Update latest build
      run: aws s3api put-object --bucket ${{ inputs.bucket }} --key ${{ inputs.product }}/${{ inputs.branch }}/latestBuild --body latestBuild
      shell: bash
