name: Run Directive
run-name: test

inputs:
  repository:
    description: 'Github repo'
    required: true
  hash:
    description: 'Github commit hash to checkout'
    required: false
    default: ''
  working-directory:
    description: 'Name of component directory'
    required: true
  config:
    description: 'Config JSON file'
    required: true
  stage:
    description: 'Name of stage'
    required: true
  directive:
    description: 'An npm directive. e.g. deploy, test'
    required: true

jobs:
  run-directive:
    name: Run Directive
    using: "composite"

    steps:
      - name: Setup Environment
        uses: Brightspace/bdp-ci-action/setup-env@master

      - name: Checkout branch
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.hash }}
          fetch-depth: 0

      - name: Use Node.js
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc

      - name: Add CodeArtifact npm registry
        uses: Brightspace/codeartifact-actions/npm/add-registry@main
        with:
          auth-token: ${{secrets.CODEARTIFACT_AUTH_TOKEN}}

      - name: Setup working directory
        run: |
          cp ${{ inputs.config }} ${{ inputs.working-directory }}/config.json
          cd ${{ inputs.working-directory }}

      - name: Run directive
        run: |
          ${{ inputs.directive }} -- --stage ${{ inputs.stage }}
