name: NPM Phase Directive

on:
  workflow_call:
    inputs:
      account:
        type: string
        description: AWS account number
        required: true
      components:
        type: string
        description: List of components to action on
        required: true
      config:
        type: string
        description: Config JSON file
        required: true
      directive:
        type: string
        description: Directive to run. e.g. test, deploy
        required: true
      hash:
        type: string
        description: Github commit hash to checkout
        required: false
        default: ''
      region:
        type: string
        description: AWS region
        required: true
      role:
        type: string
        description: Name of AWS role to assume
        required: false
        default: github-actions-ci-assumable-role
      stage:
        type: string
        description: Name of stage
        required: true

jobs:
  env-setup:
    name: Setup NPM environment
    runs-on: [ self-hosted, AWS, Linux ]
    steps:
      - name: Checkout branch
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          ref: ${{ inputs.hash }}
          fetch-depth: 0
      - name: Use Node.js
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
      - name: Add CodeArtifact npm registry
        uses: Brightspace/codeartifact-actions/npm/add-registry@main
        with:
          auth-token: ${{ secrets.CODEARTIFACT_AUTH_TOKEN }}
      - name: Set up AWS creds
        uses: Brightspace/third-party-actions@aws-actions/configure-aws-credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ inputs.region }}
          role-to-assume: "arn:aws:iam::${{ inputs.account }}:role/${{ inputs.role }}"
          role-duration-seconds: 1200
      - name: NPM CI
        run: npm ci

  run-directive:
    name: Execute NPM directive
    runs-on: [ self-hosted, AWS, Linux ]
    needs: env-setup
    strategy:
      fail-fast: false
      matrix:
        COMPONENT: ${{ fromJson(inputs.components) }}
    steps:
      - name: Run Directive (${{ matrix.COMPONENT }})
        working-directory: ${{ matrix.COMPONENT }}
        env:
          CONFIG_PATH: ${{ inputs.config }}
          DIRECTIVE: ${{ inputs.directive }}
          STAGE: ${{ inputs.stage }}
        run: npm run ${ DIRECTIVE } -- --stage ${ STAGE }
