name: 'Stage Release'
description: 'Create release package for BDP'
outputs:
  branch:
    description: Git branch
  build:
    description: Build number
runs:
  using: 'composite'
  steps:
    - run: ls -al /home/jparker/actions-runner/_work/_actions/Brightspace/bdp-ci-action/release/release/
      shell: bash
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
