name: 'Stage Release'
description: 'Create release package for BDP'
outputs:
  branch:
    description: Git branch
  build:
    description: Build number
runs:
  using: 'composite'
  steps:
    - run: |
        pwd
        ls -al
      shell: bash
    - run: ./entrypoint.sh
      shell: bash
