name: 'Stage Release'
description: 'Create release package for BDP'
outputs:
  branch:
    description: Git branch
  build:
    description: Build number
runs:
  using: 'composite'
  env:
    action_path=${{ github.action_path }}
  steps:
    - run: |
        ls -al $action_path
      shell: bash
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
