name: 'Stage Release'
description: 'Create release package for BDP'
outputs:
  branch:
    description: Git branch
  build:
    description: Build number
runs:
  using: 'composite'
  steps:
    - run: apt install tree -y
      shell: bash
    - run: tree /home/jparker/actions-runner/_work/_actions/Brightspace/bdp-ci-action/
      shell: bash
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
