name: 'Stage Release'
description: 'Create release package for BDP'
outputs:
  branch:
    description: Git branch
  build:
    description: Build number
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
