name: 'Java Build'
description: 'Use Maven to build Java project'
inputs:
  ARTIFACTORY_MAVEN:
    description: 'The Artifactory access token for Maven'
    required: true
  PROJECT_PATH:
    description: 'The relative PATH of Maven project folder'
    required: true
    default: "."
  DEPLOY:
    description: 'Flag for publishing to Artifactory'
    required: false
    default: "false"
  BRANCH:
    description: 'Git branch'
    required: false
    default: "master"
  BUILDNUM:
    description: 'CI build number'
    required: false
    default: 10000
  CODE_COVERAGE_COMMANDS:
    description: 'Additional commands to run for code coverage requirements'
    required: false
    default: "jacoco:report coveralls:report"
  DEPLOY_COMMANDS:
    description: 'Additional parameters for deployment'
    required: false
    default: ""
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ARTIFACTORY_MAVEN }}
    - ${{ inputs.PROJECT_PATH }}
    - ${{ inputs.DEPLOY }}
    - ${{ inputs.BRANCH }}
    - ${{ inputs.BUILDNUM }}
    - ${{ inputs.CODE_COVERAGE_COMMANDS }}
    - ${{ inputs.DEPLOY_COMMANDS }}
